version: "3"

services:

  app:
    container_name: plate-recognition-app
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./.env:/app/.env
    ports:
      - '8080:8080'
      #- '5678:5678'
    #entrypoint: ["sh", "-c", "uvicorn src.app.main:app --host 0.0.0.0 --port 8080 --reload"]
    entrypoint: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn src.app.main:app --host 0.0.0.0 --port 8080 --reload"]
  prometheus:
    container_name: prometheus
    build: 
      context: prometheus
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      - PLATE_RECOGNITION_APP_HOST=app