version: "3"

services:

  app:
    container_name: plate_recognition_app
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    ports:
      - '8080:80'
      - '5678:5678'
    #command: /start-reload.sh
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 -m uvicorn src.app.main:app --host 0.0.0.0 --port 80 --reload"]
