stages:
  download_data:
    cmd: python src/pipeline/download_data.py
    deps:
    - src/pipeline/download_data.py
    outs:
    - data/raw/images
    - data/raw/annotations.csv
    - data/raw/plates.csv
  make_dataset:
    cmd: python src/pipeline/make_dataset.py
    deps:
    - src/pipeline/make_dataset.py
    - data/raw/images
    - data/raw/annotations.csv
    - data/raw/plates.csv
    outs:
    - data/processed/train
    - data/processed/test
    - data/processed/validation
    params:
      - random_state    
  train_model:
    cmd: python src/pipeline/train_model.py
    deps:
    - data/processed
    - src/pipeline/train_model.py
    - src/models/fetch_model.py
    - src/models/build_model.py
    params:
    - train
    - random_state
  predict_model:
    cmd: python src/pipeline/test_model.py
    deps:
    - src/pipeline/test_model.py
    params:
    - test