stages:
  download_data:
    cmd: python src/pipeline/download_data.py
    deps:
    - src/pipeline/download_data.py
    outs:
    - data/raw/images
    - data/raw/annotations.csv
    - data/raw/plates.csv
  make_dataset:
    cmd: python src/pipeline/make_dataset.py
    deps:
    - src/pipeline/make_dataset.py
    - data/raw/images
    - data/raw/annotations.csv
    - data/raw/plates.csv
    outs:
    - data/processed/train
    - data/processed/test
    - data/processed/validation
    params:
      - random_state    
  data_expectations:
    cmd: python src/pipeline/data_expectations.py
    deps:
    - data/processed
    outs:
    - reports/great_expectations/train_annotations.json
    - reports/great_expectations/validation_annotations.json
    - reports/great_expectations/test_annotations.json
  train_model:
    cmd: python src/pipeline/train_model.py
    deps:
    - reports/great_expectations/train_annotations.json
    - reports/great_expectations/validation_annotations.json
    - reports/great_expectations/test_annotations.json
    - data/processed
    - src/pipeline/train_model.py
    - src/models/fetch_model.py
    - src/models/build_model.py
    outs:
    - reports/train/history.json
    params:
    - train
    - random_state
  test_model:
    cmd: python src/pipeline/test_model.py
    deps:
    - src/pipeline/test_model.py
    - reports/train/history.json
    params:
    - test