random_state: 42
augmentation: true

train:
  fit:
    epochs: 1000
  model:
    model_name: teste
    model_version: 1
    dropout: 0.5
    cnn_blocks: 4
    filters_num: 56
    filters_kernel_size: 3
    optimizer_name: adam
    learning_rate: 0.0635

test:
  model:  
    model_name: test
    model_version: 1
    tr_ocr_processor: microsoft/trocr-small-printed
    tr_ocr_model: microsoft/trocr-small-printed