train:
  fit:
    epochs: 10000
    save_every_n_epochs: 1000
  
  model:
    model_name: giou_v10
    model_version: 1
    dropout: 0.4
    cnn_blocks: 6
    filters_num: 32
    filters_kernel_size: 3
