{
 "title": "Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Telegram Bot (requests counter)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_messages_total{job=\"telegram-bot\"}",
     "legendFormat": "Number of text messages processed"
    },
    {
     "expr": "number_of_photos_total{job=\"telegram-bot\"}",
     "legendFormat": "Number of photos processed"
    }
   ]
  },
  {
   "title": "Plate Recognition Service (requests counter)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_model_http_requests_total)",
     "legendFormat": "Total number of requests"
    }
   ]
  },
  {
   "title": "Telegram Bot (requests timeline)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "number_of_messages_total{job=\"telegram-bot\"}",
     "legendFormat": "Number of text messages processed"
    },
    {
     "expr": "number_of_photos_total{job=\"telegram-bot\"}",
     "legendFormat": "Number of photos processed"
    }
   ]
  },
  {
   "title": "Plate Recognition Service (requests timeline)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fastapi_model_http_requests_total{handler!=\"/openapi.json\"}",
     "legendFormat": " {{handler}}"
    }
   ]
  },
  {
   "title": "Plate recognition Service (Errors ratio)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_model_http_requests_total{job=\"plate-recognition-app\", status!=\"2xx\", status!=\"3xx\"}\n/ fastapi_model_http_requests_total{job=\"plate-recognition-app\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}