apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: $PROMETHEUS_SCHEMA://$PROMETHEUS_HOST:$PROMETHEUS_PORT
