name: Deploy - Plate Recognition App - CloudRun

on:
  workflow_run:
    workflows: ["Code Checks - Plate Recognition App"]
    branches: ["production"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push-artifact-registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF_NAME }}

      -
        name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      -
        name: Build and push (GCP)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_app
          push: true
          tags: ${{ vars.APP_DOCKER_IMAGE }}


  locust-testing:
    needs: [build-and-push-artifact-registry]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF_NAME }}

      -
        name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - 
        name: Run web API from GCP image
        run: |
          docker run -p 8080:8080 ${{ vars.APP_DOCKER_IMAGE }}
      -
        name: Install Locust
        run: |
          pip install locust

      - name: Run Load Test
        run: |
          echo Waiting 300 seconds for service to fully load...
          sleep 300
          locust --host http://localhost:8080 --headless --run-time 60s -u 5 -r 1
          
  #https://github.com/google-github-actions/deploy-cloudrun
  deploy-cloudrun:
    needs: [locust-testing]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
      with:
          ref: ${{ env.GITHUB_REF_NAME }}
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.CLOUD_RUN_JSON_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ vars.APP_SERVICE_NAME }}
        image: ${{ vars.APP_DOCKER_IMAGE }}
        env_vars: |
          DAGSHUB_USERNAME=${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}
          MODEL_NAME=${{ vars.MODEL_NAME }}
          MODEL_VERSION=${{ vars.MODEL_VERSION }}
          TR_OCR_PROCESSOR=${{ vars.TR_OCR_PROCESSOR }}
          TR_OCR_MODEL=${{ vars.TR_OCR_MODEL }}
          MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}


    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
