name: Deploy - Prometheus - CloudRun

on:
  push:
    branches:
      - "production"
    paths:
      - "prometheus/*"
      - ".github/workflows/prometheus*"
  workflow_dispatch:

jobs:
  build-and-push-artifact-registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production

      -
        name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      -
        name: Build and push (GCP)
        uses: docker/build-push-action@v3
        with:
          context: prometheus/
          push: true
          tags: ${{ vars.PROMETHEUS_DOCKER_IMAGE }}
          
  #https://github.com/google-github-actions/deploy-cloudrun
  deploy-cloudrun:
    needs: [build-and-push-artifact-registry]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
      with:
          ref: production
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.CLOUD_RUN_JSON_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ vars.PROMETHEUS_SERVICE_NAME }}
        image: ${{ vars.PROMETHEUS_DOCKER_IMAGE }}
        env_vars: |
          PLATE_RECOGNITION_APP_HOST=${{ vars.PLATE_RECOGNITION_APP_HOST }}
          TELEGRAM_BOT_HOST=${{ vars.TELEGRAM_BOT_HOST }}

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
