name: Plate recognition app deploy on CloudRun

on:
  workflow_run:
    workflows: ["Plate recognition app code checks"]
    branches: ['production']
    types: 
      - completed

jobs:
  build-and-push-artifact-registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production

      -
        name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      -
        name: Setup DVC
        uses: iterative/setup-dvc@v1
      - 
        name: Pull data from DVC
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
          dvc pull models/*
      -
        name: Build and push (GCP)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ vars.APP_DOCKER_IMAGE }}


  locust-testing:
    needs: [build-and-push-artifact-registry]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: production

      -
        name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - 
        name: Run web API from GCP image
        run: |
          docker run -d -p 8080:8080 ${{ vars.APP_DOCKER_IMAGE }}
      -
        name: Install Locust
        run: |
          pip install locust

      - name: Run Load Test
        run: |
          echo Waiting 90 seconds for service to fully load...
          sleep 90
          locust --host http://localhost:8080 --headless --run-time 60s -u 10 -r 1
          
  #https://github.com/google-github-actions/deploy-cloudrun
  deploy-cloudrun:
    needs: [locust-testing]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
      with:
          ref: production
    - uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.CLOUD_RUN_JSON_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: ${{ vars.APP_SERVICE_NAME }}
        image: ${{ vars.APP_DOCKER_IMAGE }}

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
