name: Push - Plate Recognition App - DockerHub

on:
  workflow_run:
    workflows: ["Code Checks - Plate Recognition App"]
    branches: ["production"]
    types: 
      - completed


jobs:
  build-and-push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ GITHUB_REF_NAME }}
      - 
        name: Setup Python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          #cache: 'pip' # caching pip dependencies
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to   Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Setup DVC
        uses: iterative/setup-dvc@v1
      - 
        name: Pull data from DVC
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
          dvc pull models/*
      -
        name: Build and push (DockerHub)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile_app
          push: true
          tags: gianfrancodemarco/plate-recognition:latest
